### ISSUE TITLE
访问地址挂了

### ISSUE THREAD

**Issue by sunfeng90** [Hyrmm/wms-client#2]

**Comment by sunfeng90** [comment]
http://wms.hyrm.site/ 访问不了

**Comment by Hyrmm** [comment]
> http://wms.hyrm.site/ 访问不了

cdn欠费了，已经处理了，现在可以访问了

**Comment by sunfeng90** [comment]
你们没有做手机端扫码的功能吧？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月25日 21:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Hyrmm/wms-client] 访问地址挂了 (Issue #2) |

http://wms.hyrm.site/ 访问不了

cdn欠费了，已经处理了，现在可以访问了
